name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai_pr_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gather PR diff
        id: diff
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1 || true
          git diff --unified=0 origin/${{ github.base_ref }}...HEAD > diff.patch || true
          echo "Generated diff.patch with size $(wc -c < diff.patch) bytes"
      
      - name: AI Review (OpenAI-compatible API)
        env:
          MODEL_API_BASE: ${{ secrets.MODEL_API_BASE }}
          MODEL_API_KEY: ${{ secrets.MODEL_API_KEY }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
        run: |
          bash scripts/ai_pr_review.sh diff.patch > review.md
      
      - name: Post PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('review.md', 'utf8');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
